name: CMake

on:
  push:
    branches: [ windows ]
  pull_request:
    branches: [ windows ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install OpenSSL
      run: choco install -y openssl

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Configure Tutorial CMake
      run: cmake -B ${{github.workspace}}/build_tutorial -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -S tutorial

    - name: Build Tutorial
      run: cmake --build ${{github.workspace}}/build_tutorial --config ${{env.BUILD_TYPE}}
      
